version: '3'
services:
    web:
        image: python:3.10
        ports:
            - "7359:5000"
        volumes:
            - ./flask:/code
        working_dir: /code
        depends_on:
            - redis
    redis:
        image: redis
volumes:
  flask:
