version: '3'
services:
    web:
        build: ./flask
        ports:
            - "7359:5000"
        volumes:
            - flask:/code
        depends_on:
            - redis
    redis:
        image: redis
volumes:
  flask:
