version: '2'
services:
    web:
        build: .
        ports:
            - "7359:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
